  - name: 'thoughtbot-clearance'
    require_name: 'clearance'
    version: '0.4.5'
    laod: true
    source: 'http://gems.github.com'

  - name: 'thoughtbot-shoulda'
    require_name: 'shoulda'
    version: '2.9.1'
    source: 'http://gems.github.com'

  - name: 'thoughtbot-factory_girl'
    require_name: 'factory_girl'
    version: '1.1.5'
    source: 'http://gems.github.com'
